[meta]
name = "Coldseat"
author = "Ezio"
category = "Developer"
version = "0.1.1"
siteid = 766

[script]
dependencies = [ "MLFeedRaceData" ]
optional_dependencies = [ "ChampionMedals", "WarriorMedals" ]
